from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
from PyQt5.QtWidgets import QFileDialog, QMessageBox
import os
import webbrowser
import threading
from colorama import *
import art

print(Fore.GREEN)

logo = art.text2art("OSXToUSB")
print(logo)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 733)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 640, 261, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("OSXToUSB.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 60, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 80, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 700, 251, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 390, 91, 16))
        self.label_6.setObjectName("label_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 210, 241, 21))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.appPath = QtWidgets.QLabel(self.frame)
        self.appPath.setGeometry(QtCore.QRect(0, 0, 241, 21))
        self.appPath.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.appPath.setText("")
        self.appPath.setObjectName("appPath")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 410, 411, 171))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.USBName_2 = QtWidgets.QLabel(self.frame_2)
        self.USBName_2.setGeometry(QtCore.QRect(0, 0, 411, 171))
        self.USBName_2.setAcceptDrops(True)
        self.USBName_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.USBName_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.USBName_2.setText("")
        self.USBName_2.setScaledContents(False)
        self.USBName_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.USBName_2.setWordWrap(True)
        self.USBName_2.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.USBName_2.setObjectName("USBName_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 204, 71, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 190, 211, 16))
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 590, 191, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 290, 211, 16))
        self.label_8.setObjectName("label_8")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 310, 311, 21))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.USBName = QtWidgets.QLabel(self.frame_3)
        self.USBName.setGeometry(QtCore.QRect(0, 0, 311, 21))
        self.USBName.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.USBName.setText("")
        self.USBName.setObjectName("USBName")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 305, 101, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(320, 204, 111, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.Downloader = QtWidgets.QFrame(self.centralwidget)
        self.Downloader.setGeometry(QtCore.QRect(10, 119, 441, 511))
        self.Downloader.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Downloader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Downloader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Downloader.setObjectName("Downloader")
        self.frame_4 = QtWidgets.QFrame(self.Downloader)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 415, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("mavericks.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(49, 12, 141, 16))
        self.label_10.setObjectName("label_10")
        self.mavericks = QtWidgets.QPushButton(self.Downloader)
        self.mavericks.setGeometry(QtCore.QRect(290, 14, 131, 32))
        self.mavericks.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mavericks.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.mavericks.setObjectName("mavericks")
        self.frame_5 = QtWidgets.QFrame(self.Downloader)
        self.frame_5.setGeometry(QtCore.QRect(10, 50, 415, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("yosemite.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(49, 12, 141, 16))
        self.label_12.setObjectName("label_12")
        self.yosemite = QtWidgets.QPushButton(self.Downloader)
        self.yosemite.setGeometry(QtCore.QRect(290, 54, 131, 32))
        self.yosemite.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.yosemite.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.yosemite.setObjectName("yosemite")
        self.frame_6 = QtWidgets.QFrame(self.Downloader)
        self.frame_6.setGeometry(QtCore.QRect(10, 90, 415, 41))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("elcapitan.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        self.label_14.setGeometry(QtCore.QRect(49, 12, 151, 16))
        self.label_14.setObjectName("label_14")
        self.elcapitan = QtWidgets.QPushButton(self.Downloader)
        self.elcapitan.setGeometry(QtCore.QRect(290, 94, 131, 32))
        self.elcapitan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.elcapitan.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.elcapitan.setObjectName("elcapitan")
        self.frame_7 = QtWidgets.QFrame(self.Downloader)
        self.frame_7.setGeometry(QtCore.QRect(10, 130, 415, 41))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("sierra.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(49, 12, 151, 16))
        self.label_18.setObjectName("label_18")
        self.sierra = QtWidgets.QPushButton(self.Downloader)
        self.sierra.setGeometry(QtCore.QRect(290, 134, 131, 32))
        self.sierra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sierra.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.sierra.setObjectName("sierra")
        self.frame_8 = QtWidgets.QFrame(self.Downloader)
        self.frame_8.setGeometry(QtCore.QRect(10, 170, 415, 41))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_19 = QtWidgets.QLabel(self.frame_8)
        self.label_19.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("highsierra.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_8)
        self.label_20.setGeometry(QtCore.QRect(49, 12, 191, 16))
        self.label_20.setObjectName("label_20")
        self.highsierra = QtWidgets.QPushButton(self.Downloader)
        self.highsierra.setGeometry(QtCore.QRect(290, 174, 131, 32))
        self.highsierra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.highsierra.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.highsierra.setObjectName("highsierra")
        self.frame_9 = QtWidgets.QFrame(self.Downloader)
        self.frame_9.setGeometry(QtCore.QRect(10, 210, 415, 41))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_21 = QtWidgets.QLabel(self.frame_9)
        self.label_21.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("mojave.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        self.label_22.setGeometry(QtCore.QRect(49, 12, 191, 16))
        self.label_22.setObjectName("label_22")
        self.mojave = QtWidgets.QPushButton(self.Downloader)
        self.mojave.setGeometry(QtCore.QRect(290, 214, 131, 32))
        self.mojave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mojave.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.mojave.setObjectName("mojave")
        self.frame_10 = QtWidgets.QFrame(self.Downloader)
        self.frame_10.setGeometry(QtCore.QRect(10, 250, 415, 41))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_23 = QtWidgets.QLabel(self.frame_10)
        self.label_23.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("catalina.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_10)
        self.label_24.setGeometry(QtCore.QRect(49, 12, 191, 16))
        self.label_24.setObjectName("label_24")
        self.catalina = QtWidgets.QPushButton(self.Downloader)
        self.catalina.setGeometry(QtCore.QRect(290, 254, 131, 32))
        self.catalina.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.catalina.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.catalina.setObjectName("catalina")
        self.frame_11 = QtWidgets.QFrame(self.Downloader)
        self.frame_11.setGeometry(QtCore.QRect(10, 290, 415, 41))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_25 = QtWidgets.QLabel(self.frame_11)
        self.label_25.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("bigsur.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_11)
        self.label_26.setGeometry(QtCore.QRect(49, 12, 191, 16))
        self.label_26.setObjectName("label_26")
        self.bigsur = QtWidgets.QPushButton(self.Downloader)
        self.bigsur.setGeometry(QtCore.QRect(290, 294, 131, 32))
        self.bigsur.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bigsur.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.bigsur.setObjectName("bigsur")
        self.frame_12 = QtWidgets.QFrame(self.Downloader)
        self.frame_12.setGeometry(QtCore.QRect(10, 330, 415, 41))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_27 = QtWidgets.QLabel(self.frame_12)
        self.label_27.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("monterey.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_12)
        self.label_28.setGeometry(QtCore.QRect(49, 12, 191, 16))
        self.label_28.setObjectName("label_28")
        self.monterey = QtWidgets.QPushButton(self.Downloader)
        self.monterey.setGeometry(QtCore.QRect(290, 334, 131, 32))
        self.monterey.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.monterey.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.monterey.setObjectName("monterey")
        self.frame_13 = QtWidgets.QFrame(self.Downloader)
        self.frame_13.setGeometry(QtCore.QRect(10, 370, 415, 41))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_29 = QtWidgets.QLabel(self.frame_13)
        self.label_29.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("ventura.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_13)
        self.label_30.setGeometry(QtCore.QRect(49, 12, 191, 16))
        self.label_30.setObjectName("label_30")
        self.ventura = QtWidgets.QPushButton(self.Downloader)
        self.ventura.setGeometry(QtCore.QRect(290, 374, 131, 32))
        self.ventura.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ventura.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.ventura.setObjectName("ventura")
        self.frame_14 = QtWidgets.QFrame(self.Downloader)
        self.frame_14.setGeometry(QtCore.QRect(10, 410, 415, 41))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_31 = QtWidgets.QLabel(self.frame_14)
        self.label_31.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("sonoma.webp"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_14)
        self.label_32.setGeometry(QtCore.QRect(49, 12, 191, 16))
        self.label_32.setObjectName("label_32")
        self.sonoma = QtWidgets.QPushButton(self.Downloader)
        self.sonoma.setGeometry(QtCore.QRect(290, 413, 131, 32))
        self.sonoma.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sonoma.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.sonoma.setObjectName("sonoma")
        self.frame_15 = QtWidgets.QFrame(self.Downloader)
        self.frame_15.setGeometry(QtCore.QRect(10, 450, 415, 41))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_33 = QtWidgets.QLabel(self.frame_15)
        self.label_33.setGeometry(QtCore.QRect(10, 4, 31, 31))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("0003.webp"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_15)
        self.label_34.setGeometry(QtCore.QRect(49, 12, 191, 16))
        self.label_34.setObjectName("label_34")
        self.sequoia = QtWidgets.QPushButton(self.Downloader)
        self.sequoia.setGeometry(QtCore.QRect(290, 454, 131, 32))
        self.sequoia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sequoia.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.sequoia.setObjectName("sequoia")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(60, 153, 341, 16))
        self.label_35.setObjectName("label_35")
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setGeometry(QtCore.QRect(10, 140, 411, 41))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.frame_17 = QtWidgets.QFrame(self.centralwidget)
        self.frame_17.setGeometry(QtCore.QRect(10, 240, 411, 41))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(120, 252, 341, 16))
        self.label_36.setObjectName("label_36")
        self.frame_18 = QtWidgets.QFrame(self.centralwidget)
        self.frame_18.setGeometry(QtCore.QRect(10, 340, 411, 41))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(100, 352, 341, 16))
        self.label_37.setObjectName("label_37")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(10, 100, 101, 21))
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setStyleSheet("background-color: rgb(0, 136, 255);\n"
"color: rgb(255, 255, 255);")
        self.backButton.setObjectName("backButton")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.pushButton_2.raise_()
        self.label_7.raise_()
        self.pushButton_3.raise_()
        self.label_8.raise_()
        self.frame_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.frame_16.raise_()
        self.label_35.raise_()
        self.frame_17.raise_()
        self.label_36.raise_()
        self.frame_18.raise_()
        self.label_37.raise_()
        self.Downloader.raise_()
        self.backButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton_2.clicked.connect(self.selectAppPath)
        self.pushButton_4.clicked.connect(self.selectUSBDrive)

        self.pushButton_4.setEnabled(False)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.clicked.connect(self.createBootableUSB)

        self.Downloader.hide()
        self.backButton.hide()

        self.backButton.clicked.connect(self.closeDownloaderMenu)
        self.pushButton_5.clicked.connect(self.openDownloaderMenu)

        self.mavericks.clicked.connect(lambda: self.downloadMacOSInstaller("https://vk.com/s/v1/doc/Eyy-hZHCKV3hx0udbi6DrYdPuoPUAeMA-RubhWDHcfw7cenoLn0"))
        self.yosemite.clicked.connect(lambda: self.downloadMacOSInstaller("https://vk.com/doc44638855_437104980"))
        self.elcapitan.clicked.connect(lambda: self.downloadMacOSInstaller("http://updates-http.cdn-apple.com/2019/cert/061-41424-20191024-218af9ec-cf50-4516-9011-228c78eda3d2/InstallMacOSX.dmg"))
        self.sierra.clicked.connect(lambda: self.downloadMacOSInstaller("http://updates-http.cdn-apple.com/2019/cert/061-39476-20191023-48f365f4-0015-4c41-9f44-39d3d2aca067/InstallOS.dmg"))
        self.highsierra.clicked.connect(lambda: self.downloadMacOSInstaller("https://www.mediafire.com/file/xmzy0dzapr83cbl/Install_macOS_10.13.6-17G66.dmg/file"))
        self.mojave.clicked.connect(lambda: self.downloadMacOSInstaller("https://www.mediafire.com/file/bdmxmknetqit6s2/macOS_Mojave_10.14.6_%252818G103%2529.dmg/file"))
        self.catalina.clicked.connect(lambda: self.downloadMacOSInstaller("https://www.mediafire.com/file/3buyokfsw4wc7yg/macOS+Catalina+10.15.7+MAS+%5B19H2%5D.dmg/file"))
        self.bigsur.clicked.connect(lambda: self.downloadMacOSInstaller("http://swcdn.apple.com/content/downloads/14/38/042-45246-A_NLFOFLCJFZ/jk992zbv98sdzz3rgc7mrccjl3l22ruk1c/InstallAssistant.pkg"))
        self.monterey.clicked.connect(lambda: self.downloadMacOSInstaller("https://swcdn.apple.com/content/downloads/20/06/062-34032-A_4NQKPP7NYJ/rdsbqare86atoqg2lubskvr5tab2b49fsf/InstallAssistant.pkg"))
        self.ventura.clicked.connect(lambda: self.downloadMacOSInstaller("https://swcdn.apple.com/content/downloads/62/04/082-42293-A_BLBGWQXWM6/yxa6zwy8dit7wkvu39onjf7u60t235z0k0/InstallAssistant.pkg"))
        self.sonoma.clicked.connect(lambda: self.downloadMacOSInstaller("https://swcdn.apple.com/content/downloads/53/29/082-42388-A_LTM5K4K83B/kzw5ogsws338dbive3ft03rmu1ynfouspf/InstallAssistant.pkg"))
        self.sequoia.clicked.connect(lambda: self.downloadMacOSInstaller("https://swcdn.apple.com/content/downloads/51/28/082-44432-A_4NJSZXK8G5/v10fo5dlwd50fja3qbnhj7z9tp1dx41vq2/InstallAssistant.pkg"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def downloadMacOSInstaller(self, url):
        webbrowser.open(url)



    def openDownloaderMenu(self):
        self.Downloader.show()
        self.backButton.show()

    def closeDownloaderMenu(self):
        self.Downloader.hide()
        self.backButton.hide()

    def selectAppPath(self):
        dialog = QFileDialog.getOpenFileName(MainWindow)
        appPath = str(dialog)
        appPath = appPath.replace("(", "")
        appPath = appPath.replace(")", "")
        appPath = appPath.replace(", 'All Files *'", "")
        appPath = appPath.replace("'", "")
        appPath = appPath.replace(" ", "\\ ")
        self.appPath.setText(appPath)
        createinstallmedia = appPath + "/Contents/Resources/createinstallmedia"
        self.USBName_2.setText("sudo " + createinstallmedia)
        self.pushButton_2.setEnabled(False)
        self.pushButton_4.setEnabled(True)
        self.label_35.setStyleSheet("color: rgb(0, 174, 0);")

    def selectUSBDrive(self):
        dialog = QFileDialog.getExistingDirectory(MainWindow)
        self.USBName.setText(str(dialog))
        text = self.USBName_2.text()
        usbname = dialog.replace(" ", "\\ ")
        appPath = self.appPath.text()
        newText = text + " --volume " + str(usbname) + " --applicationpath " + appPath
        self.USBName_2.setText(newText)
        self.pushButton_4.setEnabled(False)
        self.pushButton_3.setEnabled(True)
        self.label_36.setStyleSheet("color: rgb(0, 174, 0);")
        self.label_37.setStyleSheet("color: rgb(211, 199, 0);")

    def createBootableUSB(self):
        self.label_37.setStyleSheet("color: rgb(0, 174, 0);")
        thread = threading.Thread(target=self.createUSBThread)
        thread.start()
        msgbox = QMessageBox()
        msgbox.setWindowTitle("Password")
        msgbox.setText("Enter the password in the terminal window")
        msgbox.exec_()

    def createUSBThread(self):
        print(Fore.BLUE)
        print("* To write macOS to an USB, you need administrator rights.")
        print("* The process of creating a bootable USB flash drive can take from 10 to 40 minutes, depending on the speed of the USB flash drive.")
        print("----------------------------------------------------------")
        print(Fore.RESET)
        command = self.USBName_2.text()
        os.system(command)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OSXToUSB"))
        self.label_2.setText(_translate("MainWindow", "OSXToUSB"))
        self.label_3.setText(_translate("MainWindow", "Create bootable USB drive with macOS"))
        self.label_4.setText(_translate("MainWindow", "v1.0"))
        self.label_5.setText(_translate("MainWindow", "Created with 💖 by ZeroxDev"))
        self.label_6.setText(_translate("MainWindow", "Command"))
        self.pushButton_2.setText(_translate("MainWindow", "Select"))
        self.label_7.setText(_translate("MainWindow", "Install macOS.app file"))
        self.pushButton_3.setText(_translate("MainWindow", "Create bootable USB"))
        self.label_8.setText(_translate("MainWindow", "USB"))
        self.pushButton_4.setText(_translate("MainWindow", "Select"))
        self.pushButton_5.setText(_translate("MainWindow", "Download"))
        self.label_10.setText(_translate("MainWindow", "OS X Mavericks 10.9.5"))
        self.mavericks.setText(_translate("MainWindow", "Download"))
        self.label_12.setText(_translate("MainWindow", "OS X Yosemite 10.10.5"))
        self.yosemite.setText(_translate("MainWindow", "Download"))
        self.label_14.setText(_translate("MainWindow", "OS X El Capitan 10.11.6"))
        self.elcapitan.setText(_translate("MainWindow", "Download"))
        self.label_18.setText(_translate("MainWindow", "macOS Sierra 10.12.6"))
        self.sierra.setText(_translate("MainWindow", "Download"))
        self.label_20.setText(_translate("MainWindow", "macOS High Sierra 10.13.6"))
        self.highsierra.setText(_translate("MainWindow", "Download"))
        self.label_22.setText(_translate("MainWindow", "macOS Mojave 10.14.6"))
        self.mojave.setText(_translate("MainWindow", "Download"))
        self.label_24.setText(_translate("MainWindow", "macOS Catalina 10.15.7"))
        self.catalina.setText(_translate("MainWindow", "Download"))
        self.label_26.setText(_translate("MainWindow", "macOS Big Sur 11.7.10"))
        self.bigsur.setText(_translate("MainWindow", "Download"))
        self.label_28.setText(_translate("MainWindow", "macOS Monterey 12.7.6"))
        self.monterey.setText(_translate("MainWindow", "Download"))
        self.label_30.setText(_translate("MainWindow", "macOS Ventura 13.7.6"))
        self.ventura.setText(_translate("MainWindow", "Download"))
        self.label_32.setText(_translate("MainWindow", "macOS Sonoma 14.7.6"))
        self.sonoma.setText(_translate("MainWindow", "Download"))
        self.label_34.setText(_translate("MainWindow", "macOS Sequoia 15.5"))
        self.sequoia.setText(_translate("MainWindow", "Download"))
        self.label_35.setText(_translate("MainWindow", "--- 1. Select macOS installer from applications ---"))
        self.label_36.setText(_translate("MainWindow", "--- 2. Select USB Flash Drive ---"))
        self.label_37.setText(_translate("MainWindow", "--- 3. Click \'Create bootable USB\' ---"))
        self.backButton.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
